DROP TABLE if exists product;
CREATE TABLE product
(
    id VARCHAR (256) PRIMARY KEY ,
    name VARCHAR (256) ,
    price NUMERIC,
    measure_unit VARCHAR (256),
    provider VARCHAR (256),
    vat_type VARCHAR (100),
    category VARCHAR(256),
    initial_date DATE,
    day_of_week VARCHAR(20),
    num_of_periods INT,
    period VARCHAR(20),
    image CLOB
);

DROP TABLE if exists OFC_USERS;

CREATE TABLE OFC_USERS
(	NOM VARCHAR (100),
     COGNOM1 VARCHAR (100),
     COGNOM2 VARCHAR (100),
     ID VARCHAR (100) PRIMARY KEY,
     CORREU VARCHAR (200) UNIQUE,
     ADRECA VARCHAR (200),
     USERNAME VARCHAR(255) UNIQUE,
     PASSWORD VARCHAR(255) NOT NULL,
     ENABLED TINYINT NOT NULL DEFAULT 1
);

DROP TABLE if EXISTS authorities;
CREATE TABLE authorities
(
    id int(11) NOT NULL AUTO_INCREMENT,
    username VARCHAR (255) NOT NULL,
    role VARCHAR (255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uni_username_role UNIQUE (role,username),
    CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES OFC_USERS (CORREU)
);

DROP TABLE if exists OFC_COMANDES;

CREATE TABLE OFC_COMANDES
(	ID VARCHAR (100) PRIMARY KEY,
     IDSUBSCRIPCIO VARCHAR (100),
     IDUSUARI VARCHAR (100),
     QUANTITAT NUMBER,
     ESOBERTA NUMBER,
     ESENVIADA NUMBER,
     DATAENTREGA DATE
    --CONSTRAINT FK_SUBSCRIPCIO FOREIGN KEY (IDSUBSCRIPCIO)
    --REFERENCES OFC_SUBSCRIPCIONS (ID) ,
    --CONSTRAINT FK_MEMBRE FOREIGN KEY (IDMEMBRE)
    --REFERENCES OFC_MEMBRES (ID)
);


DROP TABLE if exists OFC_SUBSCRIPCIONS;

CREATE TABLE OFC_SUBSCRIPCIONS
(	ID VARCHAR (100) PRIMARY KEY,
     IDPRODUCTE VARCHAR (100) NOT NULL,
     QUANTITAT NUMBER NOT NULL,
     IDUSUARI VARCHAR (100),
     DATAINICI DATE,
     DATAFI DATE,
     ESACTIU NUMBER
    --CONSTRAINT FK_MEMBRE_SUBS FOREIGN KEY (IDMEMBRE)
    --REFERENCES OFC_MEMBRES (ID)
);